// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // Use web configuration for Windows
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjWIbNHoJWvIhpZdU3V2Np5qLOSuxPIY',
    appId: '1:818671994627:web:fb3ffe1a246f85512ecb36',
    messagingSenderId: '818671994627',
    projectId: 'peak-sight',
    authDomain: 'peak-sight.firebaseapp.com',
    storageBucket: 'peak-sight.appspot.com',
    measurementId: 'G-87KZX71W9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxajUS_N-Ofw16xe1Ph0ct-96E-Nss0xc',
    appId: '1:818671994627:android:269c7a1e2b92a11b2ecb36',
    messagingSenderId: '818671994627',
    projectId: 'peak-sight',
    storageBucket: 'peak-sight.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB44uHP5NW7WIqdOYH2HrMOddbcU_b5o44',
    appId: '1:818671994627:ios:a85881ba9dfee3652ecb36',
    messagingSenderId: '818671994627',
    projectId: 'peak-sight',
    storageBucket: 'peak-sight.appspot.com',
    iosBundleId: 'com.example.licensePeaksight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB44uHP5NW7WIqdOYH2HrMOddbcU_b5o44',
    appId: '1:818671994627:ios:80861c820dacf2922ecb36',
    messagingSenderId: '818671994627',
    projectId: 'peak-sight',
    storageBucket: 'peak-sight.appspot.com',
    iosBundleId: 'com.example.licensePeaksight.RunnerTests',
  );
}
